# Ana domain: erenbezek.com
<VirtualHost *:80>
    ServerName erenbezek.com
    ServerAlias www.erenbezek.com
    DocumentRoot /var/www/html
    ErrorLog ${APACHE_LOG_DIR}/erenbezek_error.log
    CustomLog ${APACHE_LOG_DIR}/erenbezek_access.log combined
</VirtualHost>

# Subdomain: yazilim.erenbezek.com
<VirtualHost *:80>
    ServerName yazilim.erenbezek.com
    DocumentRoot /var/www/yazilim
    ErrorLog ${APACHE_LOG_DIR}/yazilim_error.log
    CustomLog ${APACHE_LOG_DIR}/yazilim_access.log combined
</VirtualHost>
